[workspace]
members = [
    "exhaust-macros",
    "xtask",
]

[package]
name = "exhaust"
version = "0.1.0"
edition = "2021"
# TODO: figure out MSRV
description = "Trait and derive macro for working with all possible values of a type (exhaustive enumeration)."
# TODO: repository
license = "MIT OR Apache-2.0"
categories = ["algorithms", "rust-patterns", "no-std"]
keywords = ["exhaustive"]

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[dependencies]
exhaust-macros = { version = "0.1.0", path = "exhaust-macros" }
itertools = {version = "0.10.3", default-features = false }