[workspace]
members = [
    "exhaust-macros",
    "xtask",
]

[package]
name = "exhaust"
version = "0.1.1"
edition = "2021"
# TODO: figure out MSRV
description = "Trait and derive macro for working with all possible values of a type (exhaustive enumeration)."
repository = "https://github.com/kpreid/exhaust/"
license = "MIT OR Apache-2.0"
categories = ["algorithms", "rust-patterns", "no-std"]
keywords = ["exhaustive"]

[features]
default = ["std"]
std = ["alloc"]
alloc = ["itertools"]

[[test]]
name = "alloc_impls"
required-features = ["alloc"]

[[test]]
name = "std_impls"
required-features = ["std"]

[dependencies]
exhaust-macros = { version = "0.1.1", path = "exhaust-macros" }
paste = "1.0.5"
# itertools is used for its powerset iterator, which is only available with alloc
itertools = { version = "0.10.3", optional = true, default-features = false, features = ["use_alloc"] }
