[package]
name = "exhaust-macros"
version = "0.3.1"
edition.workspace = true
rust-version.workspace = true
description = "Proc-macro support for the 'exhaust' library. Do not use this library directly."
repository.workspace = true
license.workspace = true
include = ["*.rs", "README.md"]

[lib]
proc-macro = true

# all tests are in other packages (though we might someday add tests of the internal helpers)
test = false

# macro documentation is located in the `exhaust` package
doc = false
doctest = false

[dependencies]
proc-macro2 = "1.0.91"
quote = "1.0.37"
syn = { version = "3.0.3", features = ["full"] }
