name: Build & Test

permissions: {}

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - ci

env:
  CARGO_TERM_COLOR: always
  # Disable incremental compilation because we aren't caching incremental compilation
  # artifacts, so they won't be useful for anything (other than maybe the exhaustive
  # builds with different features).
  CARGO_INCREMENTAL: 0

jobs:
  test:
    strategy:
      matrix:
        toolchain: [stable, beta, nightly, 1.60.0]

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.toolchain != 'stable' }}

    steps:
    - uses: actions/checkout@v4.0.0

    - name: Install Rust toolchain
      # Install exactly what we need: compiler, Cargo, clippy, rustfmt
      run: |
          rustup toolchain install "${{ matrix.toolchain }}" --profile=minimal --component=clippy --component=rustfmt
          rustup toolchain install nightly --profile=minimal
          rustup override set "${{ matrix.toolchain }}"

    # Load cache before doing any Rust builds
    - uses: Swatinem/rust-cache@v2.7.1

    # The repository does not have a versioned Cargo.lock file.
    # As a substitute, we always test on minimal and maximal versions.
    - run: cargo +nightly update -Zdirect-minimal-versions

    - name: Lint
      run: |
        cargo clippy --timings
        cargo rustdoc -- -Drustdoc::broken_intra_doc_links

    - name: Compile (no features)
      # compile is broken out so we have visibility into compile vs. run times
      run: cargo test --no-default-features --timings --no-run

    - name: Run tests (no features)
      run: cargo test --no-default-features

    - name: Compile (all features)
      # compile is broken out so we have visibility into compile vs. run times
      run: cargo test --all-features --timings --no-run

    - name: Run tests (all features)
      run: cargo test --all-features

    # Test with latest deps, but only if we can.
    # TODO: Once Cargo has the MSRV-aware resolver, this `if` will be unnecessary.
    - if: ${{ matrix.toolchain != '1.60.0' }}
      run: cargo update

    - name: Compile with updates
      if: ${{ matrix.toolchain != '1.60.0' }}
      run: cargo test --timings --no-run

    - name: Test with updates
      if: ${{ matrix.toolchain != '1.60.0' }}
      run: cargo test --timings

    # Save timing reports so we can download and view them
    # (for understanding build performance in CI)
    - name: Save cargo --timings output
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: cargo-timings ${{ matrix.toolchain }}
        path: |
          target/cargo-timings/cargo-timing-*.html

  semver:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.0.0

    - uses: Swatinem/rust-cache@v2.7.1

    - name: Check semver
      uses: obi1kenobi/cargo-semver-checks-action@v2.1
      # Use workspace target dir for cargo install's build, so that the build will be cached.
      env:
        CARGO_TARGET_DIR: target/
      with:
        package: "exhaust"

